<?php
declare(strict_types=1);

namespace Ydb\Migrations;


use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

class Version20191116170351 extends AbstractMigration
{

    public function up(Schema $schema): void
    {
        $this->addSql('TRUNCATE TABLE `ims_ewei_shop_member_message_template_type`');
        $this->addSql('
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'1\', \'订单付款通知\', \'saler_pay\', \'OPENTM405584202\', \'\', \'订单付款通知\', \'{{first.DATA}}订单编号：{{keyword1.DATA}}商品名称：{{keyword2.DATA}}商品数量：{{keyword3.DATA}}支付金额：{{keyword4.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'2\', \'自提订单提交成功通知\', \'carrier\', \'OPENTM201594720\', \'\', \'订单付款通知\', \'{{first.DATA}}自提码：{{keyword1.DATA}}商品详情：{{keyword2.DATA}}提货地址：{{keyword3.DATA}}提货时间：{{keyword4.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'3\', \'订单取消通知\', \'cancel\', \'OPENTM201764653\', \'\', \'订单关闭提醒\', \'{{first.DATA}}订单商品：{{keyword1.DATA}}订单编号：{{keyword2.DATA}}下单时间：{{keyword3.DATA}}订单金额：{{keyword4.DATA}}关闭时间：{{keyword5.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'4\', \'订单即将取消通知\', \'willcancel\', \'OPENTM201764653\', \'\', \'订单关闭提醒\', \'{{first.DATA}}订单商品：{{keyword1.DATA}}订单编号：{{keyword2.DATA}}下单时间：{{keyword3.DATA}}订单金额：{{keyword4.DATA}}关闭时间：{{keyword5.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'5\', \'订单支付成功通知\', \'pay\', \'OPENTM405584202\', \'\', \'订单支付通知\', \'{{first.DATA}}订单编号：{{keyword1.DATA}}商品名称：{{keyword2.DATA}}商品数量：{{keyword3.DATA}}支付金额：{{keyword4.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'6\', \'订单发货通知\', \'send\', \'OPENTM401874827\', \'\', \'订单发货通知\', \'{{first.DATA}}订单编号：{{keyword1.DATA}}快递公司：{{keyword2.DATA}}快递单号：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'7\', \'自动发货通知(虚拟物品及卡密)\', \'virtualsend\', \'OPENTM207793687\', \'\', \'自动发货通知\', \'{{first.DATA}}商品名称：{{keyword1.DATA}}订单号：{{keyword2.DATA}}订单金额：{{keyword3.DATA}}卡密信息：{{keyword4.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'8\', \'订单状态更新(修改收货地址)(修改价格)\', \'orderstatus\', \'TM00017\', \'\', \'订单付款通知\', \'{{first.DATA}}订单编号:{{OrderSn.DATA}}订单状态:{{OrderStatus.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'9\', \'退款成功通知\', \'refund1\', \'TM00430\', \'\', \'退款成功通知\', \'{{first.DATA}}退款金额：{{orderProductPrice.DATA}}商品详情：{{orderProductName.DATA}}订单编号：{{orderName.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'10\', \'换货成功通知\', \'refund3\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'11\', \'退款申请驳回通知\', \'refund2\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'12\', \'充值成功通知\', \'recharge_ok\', \'OPENTM207727673\', \'\', \'充值成功提醒\', \'{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'13\', \'提现成功通知\', \'withdraw_ok\', \'OPENTM207422808\', \'\', \'提现通知\', \'{{first.DATA}}申请提现金额：{{keyword1.DATA}}取提现手续费：{{keyword2.DATA}}实际到账金额：{{keyword3.DATA}}提现渠道：{{keyword4.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'14\', \'会员升级通知(任务处理通知)\', \'upgrade\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'15\', \'充值成功通知（后台管理员手动）\', \'backrecharge_ok\', \'OPENTM207727673\', \'\', \'充值成功提醒\', \'{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'16\', \'积分变动提醒\', \'backpoint_ok\', \'OPENTM207509450\', \'\', \'积分变动提醒\', \'{{first.DATA}}获得时间：{{keyword1.DATA}}获得积分：{{keyword2.DATA}}获得原因：{{keyword3.DATA}}当前积分：{{keyword4.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'17\', \'换货发货通知\', \'refund4\', \'OPENTM401874827\', \'\', \'订单发货通知\', \'{{first.DATA}}订单编号：{{keyword1.DATA}}快递公司：{{keyword2.DATA}}快递单号：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'18\', \'砍价活动通知\', \'bargain_message\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'bargain\', \'砍价消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'19\', \'拼团活动通知\', \'groups\', \'\', \'\', \'\', \'\', \'0\', \'groups\', \'拼团消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'20\', \'人人分销通知\', \'commission\', \'\', \'\', \'\', \'\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'21\', \'商品付款通知\', \'saler_goodpay\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'22\', \'砍到底价通知\', \'bargain_fprice\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'bargain\', \'砍价消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'23\', \'订单收货通知(卖家)\', \'saler_finish\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'24\', \'余额兑换成功通知\', \'exchange_balance\', \'OPENTM207727673\', \'\', \'充值成功提醒\', \'{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'exchange\', \'兑换中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'25\', \'积分兑换成功通知\', \'exchange_score\', \'OPENTM207509450\', \'\', \'积分变动提醒\', \'{{first.DATA}}获得时间：{{keyword1.DATA}}获得积分：{{keyword2.DATA}}获得原因：{{keyword3.DATA}}当前积分：{{keyword4.DATA}}{{remark.DATA}}\', \'0\', \'exchange\', \'兑换中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'26\', \'兑换中心余额充值通知\', \'exchange_recharge\', \'OPENTM207727673\', \'\', \'充值成功提醒\', \'{{first.DATA}}充值金额：{{keyword1.DATA}}充值时间：{{keyword2.DATA}}账户余额：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'exchange\', \'兑换中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'27\', \'游戏中心通知\', \'lottery_get\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'lottery\', \'抽奖消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'35\', \'库存预警通知\', \'saler_stockwarn\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'36\', \'卖家核销商品核销通知\', \'o2o_sverify\', \'OPENTM409521536\', \'\', \'核销成功提醒\', \'{{first.DATA}}核销项目：{{keyword1.DATA}}核销时间：{{keyword2.DATA}}核销门店：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'o2o\', \'O2O消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'37\', \'核销商品核销通知\', \'o2o_bverify\', \'OPENTM409521536\', \'\', \'核销成功提醒\', \'{{first.DATA}}核销项目：{{keyword1.DATA}}核销时间：{{keyword2.DATA}}核销门店：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'o2o\', \'O2O消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'38\', \'卖家商品预约通知\', \'o2o_snorder\', \'OPENTM202447657\', \'\', \'预约成功提醒\', \'{{first.DATA}}预约项目：{{keyword1.DATA}}预约时间：{{keyword2.DATA}}{{remark.DATA}}\', \'0\', \'o2o\', \'O2O消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'39\', \'商品预约成功通知\', \'o2o_bnorder\', \'OPENTM202447657\', \'\', \'预约成功提醒\', \'{{first.DATA}}预约项目：{{keyword1.DATA}}预约时间：{{keyword2.DATA}}{{remark.DATA}}\', \'0\', \'o2o\', \'O2O消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'42\', \'商品下单通知\', \'saler_goodsubmit\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'43\', \'任务接取通知\', \'task_pick\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'task\', \'任务中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'44\', \'任务进度通知\', \'task_progress\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'task\', \'任务中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'45\', \'任务完成通知\', \'task_finish\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'task\', \'任务中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'46\', \'任务海报接取通知\', \'task_poster_pick\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'task\', \'任务中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'47\', \'任务海报进度通知\', \'task_poster_progress\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'task\', \'任务中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'48\', \'任务海报完成通知\', \'task_poster_finish\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'task\', \'任务中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'49\', \'任务海报扫描通知\', \'task_poster_scan\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'task\', \'任务中心消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'50\', \'维权订单通知\', \'saler_refund\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sys\', \'系统消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'51\', \'社区会员升级通知\', \'sns\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sns\', \'人人社区消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'52\', \'成为分销商通知\', \'commission_become\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'53\', \'新增下线通知\', \'commission_agent_new\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'54\', \'下级付款通知\', \'commission_order_pay\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'55\', \'下级确认收货通知\', \'commission_order_finish\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'56\', \'提现申请提交通知\', \'commission_apply\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'57\', \'提现申请完成审核通知\', \'commission_check\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'58\', \'佣金打款通知\', \'commission_pay\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'59\', \'分销商等级升级通知\', \'commission_upgrade\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'60\', \'成为股东通知\', \'globonus_become\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'globonus\', \'股东消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'61\', \'股东等级升级通知\', \'globonus_upgrade\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'globonus\', \'股东消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'62\', \'分红发放通知\', \'globonus_pay\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'globonus\', \'股东消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'63\', \'奖励发放通知\', \'article\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'article\', \'文章营销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'64\', \'成为区域代理通知\', \'abonus_become\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'abonus\', \'区域代理消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'65\', \'省级代理等级升级通知\', \'abonus_upgrade1\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'abonus\', \'区域代理消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'66\', \'市级代理等级升级通知\', \'abonus_upgrade2\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'abonus\', \'区域代理消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'67\', \'区级代理等级升级通知\', \'abonus_upgrade3\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'abonus\', \'区域代理消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'68\', \'区域代理分红发放通知\', \'abonus_pay\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'abonus\', \'区域代理消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'69\', \'入驻申请通知\', \'merch_apply\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'merch\', \'商家通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'70\', \'提现申请提交通知\', \'merch_applymoney\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'merch\', \'商家通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'71\', \'社区会员评论通知\', \'reply\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'sns\', \'人人社区消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'72\', \'修改地址卖家通知\', \'cycelbuy_seller_address\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'cycelbuy\', \'周期购消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'73\', \'修改收货时间卖家通知\', \'cycelbuy_seller_date\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'cycelbuy\', \'周期购消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'74\', \'周期购定时发货通知\', \'cycelbuy_timing\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'cycelbuy\', \'周期购消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'75\', \'修改收货时间买家通知\', \'cycelbuy_buyer_date\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'cycelbuy\', \'周期购消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'76\', \'修改地址买家通知\', \'cycelbuy_buyer_address\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'cycelbuy\', \'周期购消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'77\', \'分销提现申请提醒\', \'commission_applymoney\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'commission\', \'分销消息通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'80\', \'成为团长通知\', \'dividend_become\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'dividend\', \'团队分红通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'81\', \'成为团长通知(卖家)\', \'dividend_become_saler\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'dividend\', \'团队分红通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'82\', \'团员成为团长通知\', \'dividend_downline_become\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'dividend\', \'团队分红通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'83\', \'团长提现通知\', \'dividend_apply\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'dividend\', \'团队分红通知\');
            INSERT INTO `ims_ewei_shop_member_message_template_type` VALUES (\'84\', \'提现审核完成通知\', \'dividend_check\', \'OPENTM207574677\', \'\', \'业务处理通知\', \'{{first.DATA}}业务类型：{{keyword1.DATA}}业务状态：{{keyword2.DATA}}业务内容：{{keyword3.DATA}}{{remark.DATA}}\', \'0\', \'dividend\', \'团队分红通知\');
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('TRUNCATE TABLE `ims_ewei_shop_member_message_template_type`');
    }
}