<?php


namespace Ydb\Util;


class Constants
{
    public const TM_COMMISSION_AGENT_NEW = 'TM_COMMISSION_AGENT_NEW';
    public const TM_COMMISSION_BECOME = 'TM_COMMISSION_BECOME';
    public const TM_COMMISSION_ORDER_PAY = 'TM_COMMISSION_ORDER_PAY';
    public const TM_COMMISSION_ORDER_FINISH = 'TM_COMMISSION_ORDER_FINISH';

    public const TM_AUTHOR_BECOME = 'TM_AUTHOR_BECOME';
    public const TM_AUTHOR_DOWN_PAY = 'TM_AUTHOR_DOWN_PAY';

    public const TM_GLOBONUS_BECOME = 'TM_GLOBONUS_BECOME';

    public const TM_DIVIDEND_APPLY = 'TM_DIVIDEND_APPLY';
    public const TM_DIVIDEND_CHECK = 'TM_DIVIDEND_CHECK';
    public const TM_DIVIDEND_PAY = 'TM_DIVIDEND_PAY';
    public const TM_DIVIDEND_BECOME = 'TM_DIVIDEND_BECOME';
    public const TM_DIVIDEND_ORDER_FINISH = 'TM_DIVIDEND_ORDER_FINISH';
    public const TM_DIVIDEND_BECOME_SALER = 'TM_DIVIDEND_BECOME_SALER';
    public const TM_DIVIDEND_APPLYMONEY = 'TM_DIVIDEND_APPLYMONEY';
    public const TM_DIVIDEND_DOWNLINE_BECOME = 'TM_DIVIDEND_DOWNLINE_BECOME';
}